### ISSUE TITLE
好像现在这个版本也不能用了

### ISSUE THREAD

**Issue by xgdyp** [ydsuper/Typora_Free_Download#1]

**Comment by ydsuper** [comment]
我是之前安装就一直没有卸载，目前还可以使用。
不能使用的话，方便截个图吗？

**Comment by jokereven** [comment]
大概是这样的:
This beta version of Typora is expired, please download and install a newer version. 
解决办法:
https://blog.csdn.net/yyywxk/article/details/125133205

**Comment by jokereven** [comment]
可以看看这个https://www.bilibili.com/video/BV1a94y1U7ao

**Comment by xgdyp** [comment]
十分感谢！我的报错也是
```
The beta version of Typora is expired, please download and install a new version
```
看了解决方案，十分感谢！
